version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS:-29sXIR7zxf}
      MYSQL_DATABASE: ${DATABASE_NAME:-cache_db}
      MYSQL_USER: ${DATABASE_USER:-dbuser}
      MYSQL_PASSWORD: ${DATABASE_PASS:-dbpass}
      TZ: 'Asia/Ho_Chi_Minh'
    networks:
      - depropstudio-network
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: depropstudio-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Ho_Chi_Minh'
    networks:
      - depropstudio-network

  app:
    build: .
    ports:
      - '8888:8080'
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cache_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    depends_on:
      - db
    container_name: depropstudio-app
    restart: always
    networks:
      - depropstudio-network

networks:
  depropstudio-network:
    driver: bridge